title: Statistical Foundations of Machine Learning - Practicals Handbook
author: Pascal Tribel
logo: sfml.png
copyright: 2026
only_build_toc_files: true
execute:
  execute_notebooks: cache
  timeout: 1000
html:
  analytics:
     google_analytics_id: "GTM-NT45RH4N"
